import { seat } from '../types/seat'

export const SEAT_DATA: seat[] = [
  { seatNum: '1', isReserved: true, isBlocked: false },
  { seatNum: '2', isReserved: false, isBlocked: false },
  { seatNum: '3', isReserved: false, isBlocked: false },
  { seatNum: '4', isReserved: false, isBlocked: false },
  { seatNum: '5', isReserved: true, isBlocked: false },
  { seatNum: '6', isReserved: false, isBlocked: false },
  { seatNum: '7', isReserved: false, isBlocked: false },
  { seatNum: '8', isReserved: false, isBlocked: false },
  { seatNum: '9', isReserved: false, isBlocked: false },
  { seatNum: '10', isReserved: false, isBlocked: false },
  { seatNum: '11', isReserved: false, isBlocked: false },
  { seatNum: '12', isReserved: false, isBlocked: false },
  { seatNum: '13', isReserved: false, isBlocked: false },
  { seatNum: '14', isReserved: false, isBlocked: false },
  { seatNum: '15', isReserved: false, isBlocked: false },
  { seatNum: '16', isReserved: false, isBlocked: false },
  { seatNum: '17', isReserved: false, isBlocked: false },
  { seatNum: '18', isReserved: false, isBlocked: false },
  { seatNum: '19', isReserved: false, isBlocked: false },
  { seatNum: '20', isReserved: false, isBlocked: false },
  { seatNum: '21', isReserved: true, isBlocked: false },
  { seatNum: '22', isReserved: false, isBlocked: false },
  { seatNum: '23', isReserved: false, isBlocked: false },
  { seatNum: '24', isReserved: false, isBlocked: false },
  { seatNum: '25', isReserved: false, isBlocked: false },
  { seatNum: '26', isReserved: false, isBlocked: false },
  { seatNum: '27', isReserved: false, isBlocked: false },
  { seatNum: '28', isReserved: false, isBlocked: false },
  { seatNum: '29', isReserved: false, isBlocked: false },
  { seatNum: '30', isReserved: false, isBlocked: false },
  { seatNum: '31', isReserved: false, isBlocked: false },
  { seatNum: '32', isReserved: false, isBlocked: false },
  { seatNum: '팀1', isReserved: false, isBlocked: false },
  { seatNum: '팀2', isReserved: false, isBlocked: false },
  { seatNum: '팀3', isReserved: false, isBlocked: false },
  { seatNum: '팀4', isReserved: false, isBlocked: false },
]
